import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "tRelloW",
  description: "Generated by Sarah Habibi for learning purposes",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-br from-lime-50 to-lime-100 h-screen">
        {children}
      </body>
    </html>
  );
}
