import type { Metadata } from "next";
import "./globals.css";
import Modal from "@/components/Modal";

export const metadata: Metadata = {
  title: "tRelloW",
  description: "Generated by Sarah Habibi for learning purposes",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-b from-white to-lime-50 h-screen">
        {children}
        <Modal />
      </body>
    </html>
  );
}
